ECHO="/bin/echo"
AWK="/usr/bin/awk"
FILES=$$(ls */*.tex | grep lecture | sed -e 's/.tex$$//')

all:populate
	pdflatex main.tex

clean:
	rm -f *.aux *.log *.toc *.scr

distclean:clean
	rm -f *.bbl *.blg main.pdf

bib:
	pdflatex main.tex
	bibtex main
	pdflatex main.tex
	pdflatex main.tex

populate:
	@echo "% Autogenerated using Makefile. DO NOT EDIT" > lectures-list.tex
	@for f in $(FILES) ; do \
		$(ECHO) "\newpage \include{$$f}" >> lectures-list.tex ;  \
	done
